In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import soundfile as sf
from pathlib import Path
import re
import os
import json

## Annotation DB

### define paths for annotations and audio files

In [33]:
selection_path = Path('../../../../multispecies_dataset')
filelist = list(selection_path.glob('**/*.csv'))
# variables_names = [x.name.split('.')[0] for x in files_list]
filelist

[PosixPath('../../../../multispecies_dataset/HYDBBA105_Calls_2018_04_2kHz.csv'),
 PosixPath('../../../../multispecies_dataset/HYDBBA105_Calls_2018_04_EvenDays_MF.csv'),
 PosixPath('../../../../multispecies_dataset/HYDBBA105_Calls_2018_04_200Hz.csv'),
 PosixPath('../../../../multispecies_dataset/HYDBBA105_AcousticEvents_2018_04_EvenDays_AllRuns_v2.csv')]

### parse .csv file into pandas df

In [53]:
metadata =[]
for i,file in enumerate(filelist):
    dfTemp = pd.read_csv(file)
    print(file)
    print(dfTemp.columns)
    print(dfTemp.shape)
#     dfTemp['filename'] = re.search(r'18\d{4,4}_\d{6,6}', file.as_posix()).group() 
#     dfTemp['StartMicInWater'] =np.amin(dfTemp['Begin Time (s)'])
#     dfTemp['EndMicInWater'] =np.amax(dfTemp['End Time (s)'])
    metadata.append(dfTemp)

# metadata = pd.concat(metadata)
# metadata.rename(columns={'Begin Time (s)': 'begin_time', 'End Time (s)': 'end_time'}, inplace=True)

../../../../multispecies_dataset/HYDBBA105_Calls_2018_04_2kHz.csv
Index(['Id', 'UID', 'UTC', 'UTCMilliseconds', 'parentID', 'parentUID',
       'LongDataName', 'BinaryFile'],
      dtype='object')
(10424, 8)
../../../../multispecies_dataset/HYDBBA105_Calls_2018_04_EvenDays_MF.csv
Index(['Id', 'UID', 'UTC', 'UTCMilliseconds', 'PCLocalTime', 'PCTime',
       'ChannelBitmap', 'SequenceBitmap', 'parentID', 'parentUID',
       'LongDataName', 'BinaryFile'],
      dtype='object')
(600331, 12)
../../../../multispecies_dataset/HYDBBA105_Calls_2018_04_200Hz.csv
Index(['Id', 'UID', 'UTC', 'UTCMilliseconds', 'parentID', 'parentUID',
       'LongDataName', 'BinaryFile'],
      dtype='object')
(4802, 8)
../../../../multispecies_dataset/HYDBBA105_AcousticEvents_2018_04_EvenDays_AllRuns_v2.csv
Index(['Run', 'ID', 'PG_UID', 'UTC', 'UTCMilliseconds', 'EndTime', 'DataCount',
       'Analyst', 'Species_ID', 'Sound_type', 'Comments', 'Unnamed: 11'],
      dtype='object')
(136, 12)

In [56]:
Calls_2018_04_2kHz, Calls_2018_04_EvenDays_MF, Calls_2018_04_200Hz,EvenDays_AllRuns_v2 = metadata

In [66]:
Calls_2018_04_2kHz.head()

,Id,UID,UTC,UTCMilliseconds,parentID,parentUID,LongDataName,BinaryFile
0,1,46000050,4/2/2018 17:45:38,791,1,1,"Whistle and Moan Detector, Contours ...",WhistlesMoans_Whistle_and_Moan_Detector_Contou...
1,2,46000051,4/2/2018 17:46:02,759,1,1,"Whistle and Moan Detector, Contours ...",WhistlesMoans_Whistle_and_Moan_Detector_Contou...
2,3,46000057,4/2/2018 17:51:01,183,1,1,"Whistle and Moan Detector, Contours ...",WhistlesMoans_Whistle_and_Moan_Detector_Contou...
3,4,46000058,4/2/2018 17:51:15,359,1,1,"Whistle and Moan Detector, Contours ...",WhistlesMoans_Whistle_and_Moan_Detector_Contou...
4,5,46000059,4/2/2018 17:51:29,830,1,1,"Whistle and Moan Detector, Contours ...",WhistlesMoans_Whistle_and_Moan_Detector_Contou...

In [63]:
EvenDays_AllRuns_v2.describe()

               ID      PG_UID  UTCMilliseconds      DataCount  Unnamed: 11
count  136.000000  136.000000       136.000000     136.000000          0.0
mean    68.500000   26.036765       492.316176    4527.044118          NaN
std     39.403892   16.500239       294.228551   19760.639029          NaN
min      1.000000    1.000000         6.000000       5.000000          NaN
25%     34.750000   12.000000       254.500000      30.750000          NaN
50%     68.500000   24.000000       485.500000     125.500000          NaN
75%    102.250000   40.000000       756.000000    1190.500000          NaN
max    136.000000   59.000000       995.000000  207768.000000          NaN

In [81]:
Calls_2018_04_EvenDays_MF.head(20)

,Id,UID,UTC,UTCMilliseconds,PCLocalTime,PCTime,ChannelBitmap,SequenceBitmap,parentID,parentUID,LongDataName,BinaryFile
0,1,39001507,2018-04-02 16:42:05.696,696,2018-04-02 09:42:05.696,2020-12-16 05:50:33.862,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
1,2,39001508,2018-04-02 16:42:05.700,700,2018-04-02 09:42:05.700,2020-12-16 05:50:33.862,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
2,3,39001509,2018-04-02 16:42:05.708,708,2018-04-02 09:42:05.708,2020-12-16 05:50:33.862,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
3,4,39001510,2018-04-02 16:42:06.157,157,2018-04-02 09:42:06.157,2020-12-16 05:50:33.862,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
4,5,39001511,2018-04-02 16:42:07.847,847,2018-04-02 09:42:07.847,2020-12-16 05:50:33.862,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
5,6,39001512,2018-04-02 16:42:07.859,859,2018-04-02 09:42:07.859,2020-12-16 05:50:33.863,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
6,7,39001513,2018-04-02 16:42:09.366,366,2018-04-02 09:42:09.366,2020-12-16 05:50:33.863,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
7,8,39001514,2018-04-02 16:42:09.996,996,2018-04-02 09:42:09.996,2020-12-16 05:50:33.863,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
8,9,39001515,2018-04-02 16:42:10.004,4,2018-04-02 09:42:10.004,2020-12-16 05:50:33.863,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
9,10,39001516,2018-04-02 16:42:10.173,173,2018-04-02 09:42:10.173,2020-12-16 05:50:33.863,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
10,11,39001517,2018-04-02 16:42:10.967,967,2018-04-02 09:42:10.967,2020-12-16 05:50:33.866,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
11,12,39001518,2018-04-02 16:42:12.145,145,2018-04-02 09:42:12.145,2020-12-16 05:50:33.866,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
12,13,39001519,2018-04-02 16:42:12.152,152,2018-04-02 09:42:12.152,2020-12-16 05:50:33.866,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
13,14,39001520,2018-04-02 16:42:12.155,155,2018-04-02 09:42:12.155,2020-12-16 05:50:33.866,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
14,15,39001521,2018-04-02 16:42:12.158,158,2018-04-02 09:42:12.158,2020-12-16 05:50:33.866,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
15,16,39001523,2018-04-02 16:42:14.300,300,2018-04-02 09:42:14.300,2020-12-16 05:50:33.866,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
16,17,39001524,2018-04-02 16:42:14.306,306,2018-04-02 09:42:14.306,2020-12-16 05:50:33.866,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
17,18,39001525,2018-04-02 16:42:14.308,308,2018-04-02 09:42:14.308,2020-12-16 05:50:33.866,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
18,19,39001526,2018-04-02 16:42:16.448,448,2018-04-02 09:42:16.448,2020-12-16 05:50:33.866,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...
19,20,39001527,2018-04-02 16:42:16.453,453,2018-04-02 09:42:16.453,2020-12-16 05:50:33.866,1,NaN,1,1,"Click Detector, Clicks",Click_Detector_Click_Detector_Clicks_20180402_...

### For Calls_2018_04_2kHz and Calls_2018_04_200Hz
* ParentID and parentUID are duplicated columns, Id and UID are similar
* * probably need only one of the mentioned 4 columns since they hold unique values
* * * LongDataName non unique - to get rid of

### For Calls_2018_04_EvenDays_MF
* ChannelBitmap and SequenceBitmap seems to be irrelevant with no meaningful values.
* * Same remarks as for Calls_2018_04_2kHz and Calls_2018_04_200Hz
* * * LongDataName could be meaningful - seperating between clicks and whistles and moans

### For EvenDays_AllRuns_v2
* Unnamed: 11 seems to be irrelevant with no meaningful values.
* * Same remarks as for Calls_2018_04_2kHz and Calls_2018_04_200Hz

In [47]:
combined_annotations.to_csv('combined_annotations.csv', index=False)